#!/bin/bash
# name: ZRAM/ZSWAP
# description: zram_desc
# icon: preload.svg
# compat: ubuntu, debian, arch, fedora, ostree, rhel, cachy
# nocontainer
# new
# systemd: yes
# reboot: yes

setup_zram () {
    if is_arch; then
        pkg_install zram-generator
        if [ -f /etc/systemd/zram-generator.conf ]; then
            prep_edit /etc/systemd/zram-generator.conf
        else
            prep_create /etc/systemd/zram-generator.conf
        fi
        sudo tee /etc/systemd/zram-generator.conf << 'EOF'
[zram0]
zram-size = min(ram / 3, 16384)
EOF
        sudo systemctl daemon-reload
        sysd_enable systemd-zram-setup@zram0.service
        sysd_start systemd-zram-setup@zram0.service
    elif is_ubuntu; then
        pkg_install zram-config
    elif is_debian; then
        pkg_install zram-tools
        if [ -f /etc/default/zramswap ]; then
            prep_edit /etc/default/zramswap
        else
            prep_create /etc/default/zramswap
        fi
        sudo tee /etc/default/zramswap << 'EOF'
ALGO=zstd
PERCENT=50
EOF
        sysd_stop zramswap
        sysd_start zramswap
    else
        zenwrn "$msg234"
        exit 100
    fi
}

setup_zswap() {
    # disable zram if enabled first, zswap and zram are not interoperable
    if is_fedora || is_ostree; then
        { rpm -qi "zram-generator" &>/dev/null; } && pkg_remove zram-generator
    elif is_debian || is_ubuntu; then
        { dpkg -s zram-config &>/dev/null; } && pkg_remove zram-config
    elif is_arch; then
        { pacman -Qi zram-generator &>/dev/null; } && pkg_remove zram-generator
    fi

    if grep -q "zswap.enabled=1" /proc/cmdline 2>/dev/null; then
        zeninf "Zswap already enabled. Skipping."
        return 0
    fi
    # prepare zswap
    ZSWAP_PARAMS="zswap.enabled=1 zswap.shrinker_enabled=1 zswap.compressor=zstd zswap.max_pool_percent=25 zswap.zpool=zsmalloc"
    if is_fedora; then
        grubbyargs_upd "$ZSWAP_PARAMS"
    elif is_ostree; then
        kargs_upd "$ZSWAP_PARAMS"
    else
        # systemd-boot
        prep_create /etc/kernel/cmdline.d/10-zswap.conf
        echo "$ZSWAP_PARAMS" | sudo tee /etc/kernel/cmdline.d/10-zswap.conf >/dev/null
        # GRUB
        prep_create /etc/default/grub.d/10-zswap.cfg
        sudo tee /etc/default/grub.d/10-zswap.cfg > /dev/null << EOF
# zswap kernel parameters for RAM optimization
# Generated by LinuxToys zswap optimizer
# To remove, delete this file and regenerate boot config
GRUB_CMDLINE_LINUX_DEFAULT="\${GRUB_CMDLINE_LINUX_DEFAULT} $ZSWAP_PARAMS"
EOF

        echo "Created zswap kernel parameters:"
        echo "  - systemd-boot: /etc/kernel/cmdline.d/10-zswap.conf"
        echo "  - GRUB: /etc/default/grub.d/10-zswap.cfg"
        bootloader_upd
    fi
}

_total_ram_kb=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
if [ "$_total_ram_kb" -gt 32000000 ] && ! is_rhel && ! is_cachy; then
    setup_zram
else
    setup_zswap
    warn "$zswapmsg"
fi
info "$rebootmsg"