#!/bin/bash
# name: Intel Xe Driver
# version: 1.0
# description: intelxe_desc
# icon: intel.png
# reboot: yes
# gpu: Intel
# compat: !fedora, !solus, !rhel, !pika, !ubuntu
# nocontainer
# hybridgpu: no

# --- Start of the script code ---
source "$SCRIPT_DIR/libs/helpers.lib"
askpass

if is_intel && [ -n "$intel_arc" ]; then
    # Extract DEVID from the Xe-compatible PCI device found by is_intel
    DEVID=$(<"$INTEL_XE_SYSFS/device")
    DEVID="${DEVID#0x}"

    if [[ -z "$DEVID" ]]; then
        die "Error: Could not detect Intel GPU device ID"
    fi

    echo "Detected Intel GPU device ID: $DEVID"
    if is_ostree; then
        kargs_upd 'i915.force_probe=!'"$DEVID" "xe.force_probe=$DEVID"
    else
        [ -f /etc/kernel/cmdline.d/10-intel-xe-enable.conf ] || { 
            # Create kernel cmdline drop-in file for systemd-based systems
            prep_create /etc/kernel/cmdline.d/10-intel-xe-enable.conf
            echo "i915.force_probe=!${DEVID} xe.force_probe=${DEVID}" | sudo tee /etc/kernel/cmdline.d/10-intel-xe-enable.conf >/dev/null

            # Also create GRUB drop-in config for GRUB-based systems
            prep_create /etc/default/grub.d/10-intel-xe-enable.cfg
            sudo tee /etc/default/grub.d/10-intel-xe-enable.cfg > /dev/null << EOF
# Enable intel Xe driver for discrete GPUs
# Generated by LinuxToys intel Xe optimizer
# Device ID: $DEVID
# To remove, delete this file and regenerate boot config
GRUB_CMDLINE_LINUX_DEFAULT="\${GRUB_CMDLINE_LINUX_DEFAULT} i915.force_probe=!${DEVID} xe.force_probe=${DEVID}"
EOF

            echo "Created kernel parameter configuration:"
            echo "  - systemd: /etc/kernel/cmdline.d/10-intel-xe-enable.conf"
            echo "  - GRUB: /etc/default/grub.d/10-intel-xe-enable.cfg"

            bootloader_upd
        }
    fi
else
    warn "No Intel Arc GPU device detected."
    exit 100
fi
if is_ubuntu; then
    sudo add-apt-repository -y ppa:kobuk-team/intel-graphics
    pkg_install intel-media-va-driver-non-free libmfx-gen1 libvpl2 libvpl-tools libva-glx2 va-driver-all vainfo
elif is_fedora || is_rhel; then
    rpmfusion_chk
    pkg_install intel-media-driver
elif is_debian; then
    enable_debian_nonfree
    pkg_install intel-media-va-driver-non-free libmfx-gen1
elif is_arch || is_cachy; then
    pkg_install intel-media-driver vpl-gpu-rt
fi
info "$rebootmsg"